version: "2.9"
services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    networks:
      - project

  app:
    image: openjdk_project:latest
    container_name: app
    networks:
      - project

networks:
  project: